# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm2YIG-M6x_j80I-t9_PYO-uF3cVF0Yo
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objs as go
import requests
from datetime import datetime, timedelta
from textblob import TextBlob

# --- Dashboard controls ---
st.sidebar.header("Dashboard Controls")
tickers = st.sidebar.multiselect(
    "Choose stocks/cryptos",
    ['AAPL', 'TSLA', 'MSFT', 'AMZN', 'BTC-USD', 'ETH-USD'],
    default=['AAPL', 'BTC-USD']
)
date_range = st.sidebar.date_input(
    "Date range",
    [datetime.now() - timedelta(days=30), datetime.now()]
)
interval = st.sidebar.selectbox("Interval", ['1m', '5m', '15m', '1h', '1d'], index=4)
ma_window = st.sidebar.slider('Moving Average Window', 5, 30, 10)
price_alert = st.sidebar.number_input("Set daily % change alert (e.g. 5%)", min_value=1, max_value=30, value=7)

st.title("💹 Advanced Real-Time Financial Analytics Dashboard")
st.markdown("Compare multiple assets, visualize trends & technicals, get latest news sentiment, and alerts for sharp price changes.")

# --- Interval guidance block ---
# Warn user about Yahoo Finance 1m interval limitation!
if interval == '1m':
    if (date_range[1] - date_range[0]).days > 7:
        st.warning("Yahoo Finance only provides 1-minute data for the **most recent 7 days**! Please select a recent, short range for 1m data.")
    else:
        st.info("1m data is only available for stocks during US market hours.")

def get_data(symbol):
    df = yf.download(symbol, start=date_range[0], end=date_range[1], interval=interval)
    # Flatten columns if MultiIndex (new yfinance behavior)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df

def fetch_news(symbol):
    # Use NewsAPI, replace YOUR_KEY with your real key
    api_key = "YOUR_NEWSAPI_KEY"
    url = f'https://newsapi.org/v2/everything?q={symbol}&apiKey={api_key}&sortBy=publishedAt'
    news = requests.get(url).json()
    return news.get('articles', [])

for ticker in tickers:
    st.subheader(f"📊 {ticker} Analytics")
    data = get_data(ticker)
    close_prices = data['Close'].dropna() if not data.empty and 'Close' in data else pd.Series(dtype=float)
    if data.empty or close_prices.shape[0] < 2:
        st.warning(f"No sufficient data for {ticker}")
        continue

    first_price = float(close_prices.iloc[0])
    last_price = float(close_prices.iloc[-1])
    pct_change = float(((last_price - first_price) / first_price) * 100)

    # --- Candlestick chart with Moving Average ---
    fig = go.Figure()
    fig.add_trace(go.Candlestick(x=data.index, open=data['Open'], high=data['High'],
                                 low=data['Low'], close=data['Close'], name='Candles'))
    fig.add_trace(go.Scatter(x=data.index, y=data['Close'].rolling(ma_window).mean(),
                             line=dict(color='orange', width=2), name=f"MA{ma_window}"))
    st.plotly_chart(fig, use_container_width=True)

    st.metric(label="Period Change (%)", value=f"{pct_change:.2f}%")
    st.metric(label="Volatility (stddev)", value=f"{float(close_prices.std()):.2f}")

    st.markdown("**Volume Chart**")
    st.area_chart(data['Volume'])

    if abs(pct_change) > price_alert:
        st.error(f"⚠️ {ticker} moved {pct_change:.2f}% in selected period! Check recent news.")

    # --- News & Sentiment analysis ---
    st.markdown("#### Latest News & Sentiment")
    news_items = fetch_news(ticker)
    for n in news_items[:5]:
        title = n['title']
        description = n.get('description', "")
        url = n['url']
        published = n['publishedAt'][:10]
        sentiment = TextBlob(title + ' ' + description).sentiment.polarity
        color = "green" if sentiment >= 0 else "red"
        st.markdown(
            f"[{title}]({url}) "
            f"<span style='color:{color}'>({'Positive' if sentiment >= 0 else 'Negative'})</span>  — *{published}*",
            unsafe_allow_html=True
        )

# --- Correlation heatmap if >1 asset ---
if len(tickers) > 1:
    price_dict = {}
    for t in tickers:
        d = get_data(t)
        if not d.empty and 'Close' in d:
            closes = d['Close'].dropna()
            if closes.shape[0] > 1:
                price_dict[t] = closes
    if price_dict:
        df_prices = pd.DataFrame(price_dict).dropna()
        if not df_prices.empty:
            corr = df_prices.pct_change().corr()
            st.write("### Asset Correlation Heatmap")
            st.dataframe(corr.style.background_gradient(cmap='coolwarm'))
        else:
            st.info("Insufficient data overlap for correlation plot.")
    else:
        st.info("No valid assets for correlation plot.")

# --- Portfolio simulator ---
st.markdown("### Portfolio Simulator")
weights = []
cols = st.columns(len(tickers))
for i, t in enumerate(tickers):
    w = cols[i].number_input(f"Weight for {t} (%)", min_value=0, max_value=100, value=int(100 // len(tickers)))
    weights.append(w)

if sum(weights) == 100 and len(weights) == len(tickers):
    price_dict = {}
    for t in tickers:
        d = get_data(t)
        if not d.empty and 'Close' in d:
            closes = d['Close'].dropna()
            if closes.shape[0] > 1:
                price_dict[t] = closes
    if price_dict:
        df_prices = pd.DataFrame(price_dict).dropna()
        if not df_prices.empty:
            port_value = df_prices.mul([w / 100 for w in weights], axis=1).sum(axis=1)
            st.line_chart(port_value)
            st.success(f"Portfolio simulated with weights: {weights}")
        else:
            st.info("Insufficient data overlap for portfolio simulation.")
    else:
        st.info("No valid assets for portfolio simulation.")
else:
    st.warning("Portfolio weights must sum to 100.")

st.caption("🔎 Built with Streamlit, yfinance, plotly, NewsAPI, and TextBlob. For true real-time streaming, use websocket APIs for crypto (advanced).")